### ISSUE TITLE
Support SLURM

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew.cluster#1]

**Comment by wlandau** [comment]
Hi @nviets, I just finished sketching an experimental SLURM plugin for `crew.cluster`. Would you be willing to try it out and see if it works for you? I wrote a couple test scripts at https://github.com/wlandau/crew.cluster/tree/main/tests/slurm. From your end, it would be great to confirm that the controller produced by [`crew_controller_slurm()`]() actually submits SLURM jobs and that `crew` tasks actually [run on different nodes than the local node](https://github.com/wlandau/crew.cluster/blob/152506c953ef7f0e976075cb83725e09296d657f/tests/slurm/minimal.R#L17). The scripts in that folder are already written to test these cases. In addition, it would be great to know what you think about

**Comment by wlandau** [comment]
Closing this issue because the initial implementation of the plugin is up, and testing can happen whenever the right folks are available.

**Comment by nviets** [comment]
Having a look!

**Comment by wlandau** [comment]
Thanks @nviets! Also cc @brendanf.

**Comment by nviets** [comment]
Your example works great! How can I pass through my own slurm template? In clustermq, I would set `options(clustermq.template = "slurm.tmpl")` and pass through arguments for partitions, resources, and so on.

**Comment by wlandau** [comment]
> Your example works great! 

That's wonderful to hear!

> How can I pass through my own slurm template? In clustermq, I would set options(clustermq.template = "slurm.tmpl") and pass through arguments for partitions, resources, and so on.

I am trying to get away from template files because I think they are confusing for most R users and inconvenient in most situations. I am opting for the formal `slurm_*` arguments in `crew_controller_slurm()`, with `script_lines` to input custom lines to the job script. You can see most of the lines that will be produced in the temporary job script using `controller$launcher$script()`.

**Comment by brendanf** [comment]
My first attempt failed, but this is because of the inconvenient way my cluster has chosen to implement the R environment module, which results in `sbatch` being invisible from R.  So I will need to make a separate container with R and all necessary packages in it... (I also have to do this for `targets` with `clustermq`, so I guess it was to be expected...)  I will report back once I get this built, although I expect I will have the same success as @nviets.

**Comment by wlandau** [comment]
[`crew_controller_slurm()`](https://wlandau.github.io/crew.cluster/reference/crew_controller_slurm.html) detects `sbatch` from `Sys.which("sbatch")` and `scancel` from `Sys.which("scancel")`, but there are arguments `command_submit` and `command_delete` where you can supply the full paths to these programs. Would that be more convenient?

**Comment by brendanf** [comment]
The default R installation on the cluster runs inside a singularity container, which perversely does not have the external `/usr/bin` mapped, so it's really not possible to run `sbatch` from R.  The only solution I've found is just to make my own container!

**Comment by nviets** [comment]
I see the `slurm_*` arguments for [memory and cpus](https://github.com/wlandau/crew.cluster/blob/main/R/crew_controller_slurm.R#L48), but how can I set the partition? My clusters have a variety of partitions for different sets of servers and resources, e.g. batch/interactive and GPU machines. Also, how is the path to R inherited by workers? In clusters, I often have a variety of R versions installed in non-standard locations. I usually control the path via the [tmpl file](https://github.com/mschubert/clustermq/blob/master/inst/SLURM.tmpl#L10). Is R_HOME inherited by the workers - is it overridable?

The slurm templates can be a bit clunky, but they allow for complete interactions with the cluster.

**Comment by nviets** [comment]
I see the `slurm_*` arguments for [memory and cpus](https://github.com/wlandau/crew.cluster/blob/main/R/crew_controller_slurm.R#L48), but how can I set the partition? My clusters have a variety of partitions for different sets of servers and resources, e.g. batch/interactive and GPU machines. Also, how is the path to R inherited by workers? In clusters, I often have a variety of R versions installed in non-standard locations. I usually control the path via the [tmpl file](https://github.com/mschubert/clustermq/blob/master/inst/SLURM.tmpl#L10). Is R_HOME inherited by the workers - is it overridable?

The slurm templates can be a bit clunky, but they allow for complete interactions with the cluster.

**Comment by brendanf** [comment]
@nviets I think you can add additional `#SBATCH ...` lines to the `script_lines` argument of `crew_controller_slurm()` if you have additional arguments to pass to SLURM.  This seems to work for me (I need to pass `--account=...`), although I am having some issues still.

It might be convenient to implement some helper to create these lines?  Along the lines of:
```
controller <- crew_controller_slurm(
    ...
    slurm_args = list(
        account = "project_00001",
        `gres:nvme` = 100,
        M = "large"
    )
)
```

Which would produce in the script:
```sh
#SBATCH --account="project_00001"
#SBATCH --gres:nvme=100
#SBATCH -M="large"
```

**Comment by brendanf** [comment]
@wlandau For me, the launcher works and the worker job starts, but it apparently never does the task.  During `controller$wait()`, each job gets canceled after 1 minute and a new one is submitted.  I've modified the script to include both additional SBATCH arguments, and to print the worker logs:

```R
controller <- crew_controller_slurm(
  name = "my_workflow",
  workers = 1L,
  seconds_idle = 300,
  script_lines = c(
    "#SBATCH --account={my_project_id}"
    # I don't need to load the R environment module, my custom R is on PATH, which is inherited by the worker
  ),
  verbose = TRUE,
  slurm_log_output = "crew_log_%A.txt"
)
```
The worker logs show:
```
> crew::crew_worker(settings = list(url = "ws://10.140.128.243:38007/107689e0026c9c7bf1d2f7a8742fe1043626c34a", maxtasks = Inf, idletime = 3e+05, walltime = Inf, timerstart = 0L, exitlinger = 100, cleanup = 1L, asyncdial = FALSE), launcher = "my_workflow", worker = 1L, instance = "107689e0026c9c7bf1d2f7a8742fe1043626c34a")
```

**Comment by brendanf** [comment]
The mirai-only test also fails for me.  Can you think of any other implementation details that might distinguish this case from clustermq, which does work?

**Comment by brendanf** [comment]
I looked a bit more in the worker log of a clustermq worker, and found that it was referring to the main machine by host name rather than IP.  I re-tried the mirai-only test using `url = paste0("ws://", Sys.info()["nodename"], ":38007")` and now it works.

Then I tried adding `host=Sys.info()["nodename"]` to the `crew_controller_slurm()` call, and now both of your test scripts execute with no problem.  So apparently this is some issue with the IP returned by `getip::getip()`, potentially resulting from the fact I'm running inside a Singularity container.

**Comment by wlandau** [comment]
So glad you figured it out!

Odd that `getip::getip(type = "local")` returns a hostname and `Sys.info()["nodename"]` returns an IP address. It's the complete opposite on the machines I have access to.

I searched everywhere, but beyond `getip::getip()`, I cannot seem to find a universal or reliable way to get the local IP address of the correct network interface of the local machine.  I would love to find a better way, and I would love to be able to recommend something for IPv6.

@mschubert, how does `clustermq` get the local IP address that the workers connect back to?

**Comment by brendanf** [comment]
@wlandau I think I wasn't clear; Clustermq (which has always worked for me) uses a host name, while mirai was using an IP.  So I tried using the host name instead of the IP in mirai, and now that works too.  For some reason my setup works with a host name, but not an IP.  Presumably this is actually because I can get the correct host name from `Sys.info()["nodename"]`, but I cannot get the correct IP from `getip::getip(type = "local")`.

**Comment by wlandau** [comment]
I see, that makes sense. I wonder, is `Sys.info()["nodename"]` safe in the general case on a local network? Because if so, I think I would like to use it instead of `getip::getip()` as a `crew` default. It would solve issues like yours, and it would allow me to drop a package dependency. @mschubert, have you had any issues using the human-readable hostname for TCP sockets? @shikokuchuo, is this a robust enough way to construct NNG websockets?

**Comment by shikokuchuo** [comment]
Technically from nanonext/NNG's perspective both numeric IPs or hostnames are equally valid/supported for both TCP and websockets. The only thing I can think of is that it does require a DNS lookup.

**Comment by shikokuchuo** [comment]
Also from experience `Sys.info()["nodename"]` is not safe for a local network esp. for custom configured linux distros. The "just-works" case assumes there is something like `avahi-daemon` installed.

**Comment by mschubert** [comment]
> I see, that makes sense. I wonder, is `Sys.info()["nodename"]` safe in the general case on a local network? Because if so, I think I would like to use it instead of `getip::getip()` as a `crew` default. It would solve issues like yours, and it would allow me to drop a package dependency. @mschubert, have you had any issues using the human-readable hostname for TCP sockets?

I found `Sys.info()["nodename"]` to be more reliable because it will (usually) resolve the host on all local network interfaces, while the IP address is specific to one interface. But when you have the right interface, the IP should always work if the hostname does.

The only issues I saw were (1) when `localhost` did not resolve to `127.0.0.1` (hence `clustermq` uses IP for multicore), and (2) when two interfaces are resolved but one did not allow incoming connections (hence we've got the `clustermq.host` option to set an interface manually)

**Comment by shikokuchuo** [comment]
@wlandau just FYI as I am only starting to experiment, but it seems using the hostname may make it easier for authenticating TLS certificates.

**Comment by wlandau** [comment]
Thanks, that's useful to know. Maybe a solution to https://github.com/wlandau/crew/issues/74, depending on what else your experiments find?

**Comment by shikokuchuo** [comment]
Actually an IP address works equally well, we can choose either if we're creating a certificate ourselves.

It might just be slightly more compatible with existing certificates, e.g. one generated by openssl previously, which is more likely to use a hostname than an IP.

**Comment by cfljam** [comment]
Thanks Will for another great addition to the targets-verse
I am able to run my test pipeline on SLURM using crew_controller_slurm only when I set a required walltime flag for SBATCH via  
```
script_lines = c(
      "#SBATCH --time=00:30:00")
```
It would be much simpler to tune requirements for heterogeneous targets if a slurm_walltime argument was provided so this could be set as for the companion arguments slurm_memory_gigabytes_per_cpu and slurm_cpus_per_task

**Comment by wlandau** [comment]
Good idea, the (few) SLURM clusters I have used in the past seem to require an explicitly set wall time. (@brendanf and @nviets, please correct me if I am wrong on this.) Implemented in efc4b5ab6c2718155da2b5e2284531b28f7efd87.

**Comment by brendanf** [comment]
Agreed, this is helpful.  I believe my cluster does let me submit a job without an explicit walltime, but the default is 1 minute, which is rarely useful in a real setting (although it was good enough for the tests earlier in this thread).

Incidentally, does the crew controller recover and resubmit jobs if a worker is killed by slurm due to time-out (or anything else)?  I guess this would rely on the connection between the worker and the controller timing out?

**Comment by wlandau** [comment]
> Agreed, this is helpful. I believe my cluster does let me submit a job without an explicit walltime, but the default is 1 minute, which is rarely useful in a real setting (although it was good enough for the tests earlier in this thread).

Thanks! What would be a good default value? I currently set it to 1 day, but could adjust.

> Incidentally, does the crew controller recover and resubmit jobs if a worker is killed by slurm due to time-out (or anything else)? I guess this would rely on the connection between the worker and the controller timing out?

It should, and yes it relies on the network connections. crew uses counters in mirai to detect if a worker did not complete all its assigned tasks, and it uses that information to resubmit the worker to run its backlog and potentially new tasks.

**Comment by brendanf** [comment]
> What would be a good default value? I currently set it to 1 day, but could adjust.

I think that is an ok default; it is long enough that many basic pipelines will be able to complete (or at least the worker will complete some targets before it times out), but also within the limits for the default partition on all the Slurm clusters I have used.  Users who know that they don't need their workers to live that long should give a smaller value, because shorter jobs may get scheduled faster if the cluster utilization is high, but that is made easy by providing it as an argument.

**Comment by brendanf** [comment]
> > I see, that makes sense. I wonder, is `Sys.info()["nodename"]` safe in the general case on a local network? Because if so, I think I would like to use it instead of `getip::getip()` as a `crew` default. It would solve issues like yours, and it would allow me to drop a package dependency. @mschubert, have you had any issues using the human-readable hostname for TCP sockets?
> 
> I found `Sys.info()["nodename"]` to be more reliable because it will (usually) resolve the host on all local network interfaces, while the IP address is specific to one interface. But when you have the right interface, the IP should always work if the hostname does.
> 
> The only issues I saw were (1) when `localhost` did not resolve to `127.0.0.1` (hence `clustermq` uses IP for multicore), and (2) when two interfaces are resolved but one did not allow incoming connections (hence we've got the `clustermq.host` option to set an interface manually)

While troubleshooting other issues, I have been able to confirm that (2) is what is going on for me.  Nodes on my cluster have both ethernet and infiniband.  `getip::getip()` returns the address of the ethernet adapter, but they can only talk to each other via the infiniband.  If I look up the IP address of the infiniband manually and pass it as `host` to `crew_slurm_controller()` then the tests work.

**Comment by mschubert** [comment]
> If I look up the IP address of the infiniband manually and pass it as `host`

Note that for any `clustermq` backend you can also use the interface name as `host`, e.g. `ib0` for a previous infiniband I was using (check `ifconfig` or `ip addr`)

**Comment by brendanf** [comment]
@mschubert Sadly that doesn't seem to work in `mirai`; `crew_controller_slurm()` fails with `initial sync with dispatcher timed out after 10s`.
