### ISSUE TITLE
sbatch: error: Invalid --mem-per-cpu specification with slurm_memory_gigabytes_per_cpu = 1.5

### ISSUE THREAD

**Issue by kendonB** [wlandau/crew.cluster#22]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew.cluster/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew.cluster/blob/main/CONTRIBUTING.md).
* [ ] Confirm that your issue is a genuine bug in the `crew.cluster` package itself and not a user error, known limitation, or issue from another package that `crew.cluster` depends on.
Not 100% this isn't a SLURM system issue.
* [x] If there is [already a relevant issue](https://github.com/ropensci/crew.cluster/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one]
Quite difficult for a SLURM issue

## Description

When using `crew_controller_slurm(..., slurm_memory_gigabytes_per_cpu = 1.5, ...)` I get the error:

```
sbatch: error: Invalid --mem-per-cpu specification
```
It seems to be related to having the decimal GBs. Perhaps you could just change it in the background to use `#SBATCH --mem-per-cpu=3072M` and round to the nearest integer?

## Diagnostic information

```
 crew           0.4.1      2023-09-07 [1] Github (wlandau/crew@948c339)
 crew.cluster * 0.1.1.9001 2023-08-08 [1] Github (wlandau/crew.cluster@5bb4dea)

08:28:17 mahuika01 ~ $ sinfo -o %v
VERSION
23.02.2
```

**Comment by wlandau** [comment]
Please let me know if 5817accdbc12bd9e463f51f757c53deb3e364eb6 doesn't work.
