### ISSUE TITLE
Make partition configurable for slurm clusters

### ISSUE THREAD

**Issue by kkmann** [wlandau/crew.cluster#24]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew.cluster/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew.cluster/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/crew.cluster/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a GitHub discussion.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

I would like to make the slurm partition configurable for slurm controllers. I would add a new argument `partition` to `crew_controller_slurm()` https://github.com/wlandau/crew.cluster/blob/d4234c4aab457534579f682daa130904bf1c3382/R/crew_controller_slurm.R#L26 that is then used to set the `--partition=` option for the sbatch script defined in https://github.com/wlandau/crew.cluster/blob/d4234c4aab457534579f682daa130904bf1c3382/R/crew_launcher_slurm.R#L265-L304

**Comment by wlandau** [comment]
Fixed in #25.
