### ISSUE TITLE
Capturing scheduler logs

### ISSUE THREAD

**Issue by multimeric** [wlandau/crew.cluster#43]
## Proposal

Currently, `crew.cluster` doesn't attempt to capture scheduler logs. For example with Slurm, we just pipe them all to `/dev/null` by default: https://wlandau.github.io/crew.cluster/reference/crew_controller_slurm.html#arg-slurm-log-error.

However, the scheduler logs are important. Most notably they can capture errors that happen in between tasks. As a simple example that I reported [in this issue](https://github.com/ropensci/targets/discussions/1304), I had a situation where targets only reported that crew was failing:
```
Last error message:
    {crew} worker 1 launched 5 times in a row without completing any tasks. Either troubleshoot or raise launch_max above 5. 
```

I was only able to work out the underlying error by setting `slurm_log_error=NULL` in the controller so that the logs were generated as normal, finding the appropriate log file, and then finding that the worker was running out of memory *while sending data back to the master process*:
```
Error in send(ctx, data = data, mode = 3L, block = TRUE) :
  'R_Realloc' could not re-allocate memory (1744830464 bytes)
Calls: <Anonymous> -> do.call -> <Anonymous> -> send
```

For this reason, I strongly think that we should automatically be piping the scheduler logs to a `crew`-controlled directory, and then reading them in. 

The tricky question is what API should `crew`/`crew.cluster`/`targets` provide to access these logs. I wonder if the `crew` controllers could get a new method like `$read_logs()` which returns the logs as a character vector, which the controllers (launchers?) can implement. I'm not sure about the `targets` interface for this because it needs an on-disk copy of all the metadata. Could we run `$read_logs()` on the controller and copy that into the targets store somehow?

**Comment by wlandau** [comment]
Unfortunately, there is so much variability in how schedulers automatically assign log name that `crew` is not in a position to  make assumptions about where to locate each log, even if a log directory is specified. I went ahead and put the full worker name in the error message: https://github.com/wlandau/crew/commit/b0b529422fdc4805d136f29d4ba40fd7bd4d4a62. That will make it much easier to find the correct log file.

**Comment by multimeric** [comment]
Thanks for the worker name update. However I think even easier log access would make targets much more usable on HPC. After this update, you still need to specify a custom log path for the worker, then once it fails, map the worker name to the job ID, and then look up the log file location for that job.

What I'm suggesting is that by default the controller sets the log location, so that it knows its precise location. I'm happy to write the PR as well. I mostly have experience with Slurm, do the other schedulers not allow specifying a precise log path per job?
