### ISSUE TITLE
Add `slurm_memory ` to `crew_controller_slurm`

### ISSUE THREAD

**Issue by multimeric** [wlandau/crew.cluster#44]
## Proposal

Currently we only have [`slurm_memory_gigabytes_per_cpu`](https://wlandau.github.io/crew.cluster/reference/crew_controller_slurm.html#arg-slurm-memory-gigabytes-per-cpu) for controlling the Slurm memory allocation. Unfortunately, I don't think `--mem-per-cpu` is the most intuitive argument to be configuring. For one, Slurm might decide to give you double the amount of memory that you requested because of hyperthreading ([see discussion here](https://slurm.schedmd.com/sbatch.html#OPT_mem-per-cpu)). Secondly, multithreading isn't enormously popular in R, especially when we already have parallelism provided by `targets`. Instead, I prefer [`--mem`](https://slurm.schedmd.com/sbatch.html#OPT_mem) which just simply sets the total memory per job.

Of course, you can currently configure this using:
```R
    script_lines = c(
      "#SBATCH --mem 500G",
      ...
    )
```

However, making it a first-class argument would be even more user friendly.

**Comment by wlandau** [comment]
That's a good idea, implemented in 248d6e27753a76bd1566a5533347819e29a41015
