### ISSUE TITLE
implement nextflow feature of rerun job with larger resources if not enough

### ISSUE THREAD

**Issue by stemangiola** [wlandau/crew.cluster#48]
## Prework

* [x ] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew.cluster/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/crew.cluster/blob/main/CONTRIBUTING.md).
* [x ] If there is [already a relevant issue](https://github.com/wlandau/crew.cluster/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a GitHub discussion.
* [x ] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Nextflow has a very popular option that if your job fails for not-enough resources, it relaunches the job with more resources.  Is it possible to have it in the target/crew echosystsem? Or the design does not allow it? It would be a game changer.

**Comment by stemangiola** [comment]
This is a good post explaining it

https://lucacozzuto.medium.com/handling-failing-jobs-with-nextflow-24405b97b679

The way they do it is pretty elegant

```
process {
  queue = 'queu_name'
  memory='12G'
  container = 'my_container'
  withLabel: big_time_cpus {
	memory = '45G'
        time = '48h'
        cpus = 20
  }
  withLabel: retry_increasing_mem {
       errorStrategy = 'retry'
       memory = {3.GB * task.attempt}
       cpus = 1
       time = {6.h * task.attempt}
       maxRetries = { task.exitStatus == 140 ? 4 : 1 }
  }	
}
```

Although I would prefer (for my work) to specify something like (for three attempts)

mem_Gb = c(5, 20, 200)
time_h = c(0.5, 2, 12)

As the size of my data is exponentially distributed (many small datasets, and few huge ones)

**Comment by wlandau** [comment]
This feature turned out to be much easier to implement than I originally thought. Added in https://github.com/wlandau/crew.cluster/pull/49

**Comment by wlandau** [comment]
C.f. https://github.com/wlandau/crew.cluster/pull/49#issuecomment-2605750205, I am rethinking this feature at the `crew` level: https://github.com/wlandau/crew/issues/193
