### ISSUE TITLE
SLURM workers error and main process left running

### ISSUE THREAD

**Issue by Aariq** [wlandau/crew.cluster#50]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew.cluster/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/crew.cluster/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `crew.cluster` package itself and not a user error, known limitation, or issue from another package that `crew.cluster` depends on.
* [x] If there is [already a relevant issue](https://github.com/wlandau/crew.cluster/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I noticed today that the main targets job had been running for 18+ hours with no progress on a pipeline that should have been done in a few hours.  Only the main process was running with no workers still running.  Tried restarting the job and all the workers launched and then shut down after about 10 seconds but the main process is still running.  The worker error logs all end in:

```r
Error in dial(sock, url = url, autostart = asyncdial || NA, tls = tls,  : 
  31 | Connection shutdown
Calls: <Anonymous> ... do.call -> <Anonymous> -> dial_and_sync_socket -> dial
Execution halted
```

## Reproducible example

Sorry, I don't know how to make this reproducible.  This is the relevant controller spec:

```r
controller_hpc_heavy <- 
  crew.cluster::crew_controller_slurm(
    name = "hpc_heavy",
    workers = 3, 
    tasks_max = 20,
    seconds_idle = 1000,
    options_cluster = crew_options_slurm(
      script_lines = c(
        "#SBATCH --account theresam",
        "export LD_PRELOAD=/opt/ohpc/pub/libs/gnu13/openblas/0.3.21/lib/libopenblas.so",
        "module load gdal/3.8.5 R/4.4 eigen/3.4.0"
      ),
      log_output = "logs/crew_heavy_log_%A.out",
      log_error = "logs/crew_heavy_log_%A.err",
      memory_gigabytes_per_cpu = 5,
      cpus_per_task = 7, 
      time_minutes = 360, 
      partition = "standard"
    )
  )

```

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

I expected terminated workers to eventually terminate the main process

## Diagnostic information

Full log from a failed worker:

```
R version 4.4.0 (2024-04-24)
• Platform: x86_64-pc-linux-gnu
• Running under: Rocky Linux 9.4 (Blue Onyx)
• 
• Matrix products: default
• BLAS/LAPACK: /opt/ohpc/pub/libs/gnu13/openblas/0.3.21/lib/libopenblasp-r0.3.21.so;  LAPACK version 3.9.0
• 
• locale:
•  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
•  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
•  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
•  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
•  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
• [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
• 
• time zone: America/Phoenix
• tzcode source: system (glibc)
• 
• attached base packages:
• [1] stats     graphics  grDevices datasets  utils     methods   base     
• 
• loaded via a namespace (and not attached):
•  [1] mirai_1.3.1       utf8_1.2.4        later_1.4.1       R6_2.5.1         
•  [5] tidyselect_1.2.1  magrittr_2.0.3    crew_0.10.2       glue_1.8.0       
•  [9] nanonext_1.4.0    tibble_3.2.1      pkgconfig_2.0.3   lifecycle_1.0.4  
• [13] ps_1.8.1          promises_1.3.2    cli_3.6.3         fansi_1.0.6      
• [17] processx_3.8.4    vctrs_0.6.5       getip_0.1-4       renv_1.0.11      
• [21] data.table_1.16.2 compiler_4.4.0    tools_4.4.0       pillar_1.9.0     
• [25] Rcpp_1.0.13-1     yaml_2.3.10       rlang_1.1.4      
Error in dial(sock, url = url, autostart = asyncdial || NA, tls = tls,  : 
  31 | Connection shutdown
Calls: <Anonymous> ... do.call -> <Anonymous> -> dial_and_sync_socket -> dial
Execution halted
```

**Comment by Aariq** [comment]
This is no longer a problem after I increased the number of CPUs from 7 to 8, so either it was a OOM error that wasn't properly handled, or it was some temporary issue with the HPC.

**Comment by wlandau** [comment]
Glad you figured it out.

**Comment by Aariq** [comment]
Hmm... this does actually seem to be something regarding my HPCs upgrade to RHEL9.  Once I figure it out a little more, I'll open a discussion.

**Comment by wlandau** [comment]
I actually just ran into this same issue in a pipeline last week. My company's on-prem SGE cluster just upgraded to RHEL9, and some sort of interaction between `crew` and [Splunk](https://www.splunk.com/en_us/products/infrastructure-monitoring.html) was overburdening the nodes somehow. We don't know the exact reason, but a likely hypothesis is that `crew` creates a separate NNG websocket connection for each worker. If `crew` adopts https://github.com/shikokuchuo/mirai/pull/170 (FYI @shikokuchuo), this might simplify the networking requirements and avoid conflicts with other tools.

**Comment by Aariq** [comment]
Ok, good to hear.  This is kind of driving me nuts because I can't seem to reproduce it today (but was getting consistent errors yesterday).  I'll keep investigating and let you know if I come up with anything interesting

**Comment by Aariq** [comment]
If it helps, it seems like I can now consistently get this error from the _second_ worker that is launched.  It seems my tests yesterday were working because the tasks completed fast enough that a second worker never got launched.

**Comment by Aariq** [comment]
Oh interesting!  I think possibly the issue is fixed on my HPC now?  After they finished the migration to RHEL9 and the last release of `targets` (which I mistook for the `crew` update to use the new`mirai`) my very simple test with two workers seemed to work. I just tested with the most recent releases of targets, crew, and crew.cluster and it also works.  If I encounter this problem again, I'll definitely pass this info along to the HPC folks.  Thanks.

**Comment by Aariq** [comment]
I'm still trying to debug this with the HPC folks and since the error seems to be coming from `mirai`'s `dial_and_sync_socket()` function, I thought I'd try to make a reprex just using `mirai`, but I'm a bit lost on how to do that after inspecting `crew.cluster` code and looking at the `mirai` docs.  Do you happen to have any tips for creating a reprex with just `mirai`?

**Comment by Aariq** [comment]
Just to complete the story here, I finally figured out what was going wrong here.  It is that with the upgrade to RHEL9, the default IP uses a network card that can only be used by administrators and I need to supply not the default IP as the host.  Got it working with just `mirai` thanks to [this discussion](https://github.com/r-lib/mirai/discussions/260), and working on getting it to work with crew.cluster, and then with targets again.

**Comment by shikokuchuo** [comment]
@Aariq if you try the latest dev version of [mirai](https://github.com/r-lib/mirai), this has an upgraded `host_url()`, which returns a vector of IP addresses where you have multiple network adapters. You should be able to find the one you want amongst them.

**Comment by Aariq** [comment]
> [@Aariq](https://github.com/Aariq) if you try the latest dev version of [mirai](https://github.com/r-lib/mirai), this has an upgraded `host_url()`, which returns a vector of IP addresses where you have multiple network adapters. You should be able to find the one you want amongst them.

I'll check it out!  Thanks

**Comment by Aariq** [comment]
> That's good to know, thanks! You're welcome to continue the discussion at [nanonext](https://github.com/r-lib/nanonext) as the underlying implementation is at `nanonext::ip_addr()`. Out of curiosity, how would that help vs. e.g. just trying each IP address, as I'm guessing those interface names would also be very cryptic?

No, you're right, the interface names are cryptic.  It just seems less mysterious and arbitrary to say `host = host_url()["enp1s0f1np1"]` than `host = host_url()[3]`.  E.g. I will eventually replace this line with one of those: https://github.com/cct-datascience/targets-uahpc/blob/c1a9c1da50ee7ecaa59b40a1c4ab60c86706d15d/_targets.R#L27

**Comment by shikokuchuo** [comment]
That's interesting. I guess using a fixed index wouldn't be robust as items get added depending on whether you're connected to wi-fi or a VPN etc. so it seems using an interface name may be the better option. I'm implementing your suggestion in https://github.com/r-lib/nanonext/pull/132.

**Comment by wlandau** [comment]
At the very least, those cryptic interface names could make it easier find the right output from `ip`/`ifconfig`.
